<script setup lang="ts">
// What a segment is, chosen from a terminology: a category ("Tissue"), a type ("Liver") and, where
// the type offers them, a modifier ("left"). Choosing one names the segment after it and colours
// it the way the terminology recommends, as the terminology selector of Slicer does - unless a
// name or a colour of one's own is given below, which is then kept as one's own (the desktop's
// navigator has the same two boxes, each with a button back to the terminology's).
import { computed, inject, ref, watch } from "vue";
import { RotateCcw, Search, X } from "@lucide/vue";
import type { SlicerBridge } from "@/core/bridge";

const props = defineProps<{ segmentationNodeId: string; segmentId: string; segmentName: string }>();
const emit = defineEmits<{ close: []; applied: [] }>();
const bridge = inject<SlicerBridge>("bridge")!;

interface Coded { codeValue: string; name: string; color?: string; modifierCount?: number }
interface Current {
  name: string; color: string; nameAutoGenerated: boolean; colorAutoGenerated: boolean;
  terminologyName: string; categoryCodeValue: string; typeCodeValue: string; modifierCodeValue: string;
}

const terminologyName = ref("");
const terminologies = ref<string[]>([]);
const search = ref("");
const categories = ref<Coded[]>([]);
const types = ref<Coded[]>([]);
const modifiers = ref<Coded[]>([]);
const category = ref<string>("");
const type = ref<string>("");
const modifier = ref<string>("");
const error = ref("");
// A name or colour of one's own; null means the terminology's
const ownName = ref<string | null>(null);
const ownColor = ref<string | null>(null);

const chosenType = computed(() => types.value.find((t) => t.codeValue === type.value));
const chosenModifier = computed(() => modifiers.value.find((m) => m.codeValue === modifier.value));
const terminologyNameOfSegment = computed(() => chosenModifier.value?.name ?? chosenType.value?.name ?? "");
const terminologyColor = computed(() => chosenModifier.value?.color ?? chosenType.value?.color ?? "#888888");
const resultingName = computed(() => ownName.value ?? (terminologyNameOfSegment.value || props.segmentName));
const resultingColor = computed(() => ownColor.value ?? terminologyColor.value);

async function loadCategories() {
  categories.value = await bridge.call<Coded[]>("terminologyCategoryList", [terminologyName.value, search.value]);
  if (!categories.value.some((c) => c.codeValue === category.value)) {
    category.value = categories.value[0]?.codeValue ?? "";
  }
}

async function loadTypes() {
  types.value = category.value
    ? await bridge.call<Coded[]>("terminologyTypeList", [terminologyName.value, category.value, search.value])
    : [];
  if (!types.value.some((t) => t.codeValue === type.value)) type.value = types.value[0]?.codeValue ?? "";
}

async function loadModifiers() {
  modifiers.value = type.value
    ? await bridge.call<Coded[]>("terminologyModifierList", [terminologyName.value, category.value, type.value])
    : [];
  if (!modifiers.value.some((m) => m.codeValue === modifier.value)) modifier.value = "";
}

async function start() {
  error.value = "";
  terminologies.value = await bridge.call<string[]>("terminologyNames");
  const current = await bridge.call<Current>("getSegmentTerminology", [props.segmentationNodeId, props.segmentId]);
  terminologyName.value = current.terminologyName || terminologies.value[0] || "";
  category.value = current.categoryCodeValue;
  type.value = current.typeCodeValue;
  modifier.value = current.modifierCodeValue;
  ownName.value = current.nameAutoGenerated ? null : current.name;
  ownColor.value = current.colorAutoGenerated ? null : current.color;
  await loadCategories();
  await loadTypes();
  await loadModifiers();
}

watch(() => [props.segmentationNodeId, props.segmentId].join(), start, { immediate: true });
watch(search, async () => { await loadCategories(); await loadTypes(); await loadModifiers(); });
watch(terminologyName, async () => { await loadCategories(); await loadTypes(); await loadModifiers(); });

async function chooseCategory(codeValue: string) {
  category.value = codeValue;
  type.value = "";
  modifier.value = "";
  await loadTypes();
  await loadModifiers();
}

async function chooseType(codeValue: string) {
  type.value = codeValue;
  modifier.value = "";
  await loadModifiers();
}

/** A name typed in is one's own; typed back to the terminology's (or to nothing) it is the terminology's again. */
function setOwnName(value: string) {
  ownName.value = value && value !== terminologyNameOfSegment.value ? value : null;
}

async function apply() {
  error.value = "";
  try {
    await bridge.call("setSegmentTerminology",
      [props.segmentationNodeId, props.segmentId, terminologyName.value, category.value, type.value, modifier.value,
        ownName.value, ownColor.value]);
    emit("applied");
    emit("close");
  } catch (e: any) {
    error.value = e?.message ?? String(e);
  }
}
</script>

<template>
  <div class="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 p-4" @click.self="emit('close')">
    <div class="flex max-h-[85vh] w-full max-w-3xl flex-col rounded-lg border border-input bg-popover shadow-2xl"
      data-name="terminologySelector">
      <div class="flex items-center gap-2 border-b border-input px-3 py-2">
        <span class="flex-1 text-[14px] font-medium text-foreground">What is "{{ segmentName }}"?</span>
        <button type="button" class="text-muted-foreground hover:text-highlight" title="Close" @click="emit('close')">
          <X :size="16" />
        </button>
      </div>

      <div class="flex items-center gap-2 border-b border-input px-3 py-2">
        <select v-if="terminologies.length > 1" v-model="terminologyName"
          class="h-7 max-w-[45%] rounded-md border border-input bg-background px-2 text-[12px] text-foreground outline-none">
          <option v-for="t in terminologies" :key="t" :value="t">{{ t }}</option>
        </select>
        <div class="relative flex-1">
          <Search :size="13" class="pointer-events-none absolute top-2 left-2 text-muted-foreground" />
          <!-- Bound by hand rather than with v-model, so that the lists follow every keystroke on a phone too -->
          <input :value="search" type="search" placeholder="Search for a type (liver, tumor, …)" data-name="terminologySearch"
            class="h-7 w-full rounded-md border border-input bg-background pr-2 pl-7 text-[13px] text-foreground outline-none focus:border-primary"
            @input="search = ($event.target as HTMLInputElement).value" />
        </div>
      </div>

      <div class="grid min-h-0 flex-1 grid-cols-3 divide-x divide-input">
        <div class="flex min-h-0 flex-col">
          <div class="px-3 py-1 text-[11px] tracking-wide text-muted-foreground uppercase">Category</div>
          <div class="min-h-0 flex-1 overflow-y-auto" data-name="terminologyCategories">
            <button v-for="c in categories" :key="c.codeValue" type="button"
              class="block w-full px-3 py-1 text-left text-[13px]"
              :class="c.codeValue === category ? 'bg-accent text-foreground' : 'hover:bg-accent/40'"
              @click="chooseCategory(c.codeValue)">{{ c.name }}</button>
            <div v-if="!categories.length" class="px-3 py-1 text-[12px] text-muted-foreground">Nothing matches.</div>
          </div>
        </div>
        <div class="flex min-h-0 flex-col">
          <div class="px-3 py-1 text-[11px] tracking-wide text-muted-foreground uppercase">Type</div>
          <div class="min-h-0 flex-1 overflow-y-auto" data-name="terminologyTypes">
            <button v-for="t in types" :key="t.codeValue" type="button"
              class="flex w-full items-center gap-2 px-3 py-1 text-left text-[13px]"
              :class="t.codeValue === type ? 'bg-accent text-foreground' : 'hover:bg-accent/40'"
              @click="chooseType(t.codeValue)">
              <span class="h-3 w-3 shrink-0 rounded-sm" :style="{ background: t.color }" />{{ t.name }}
            </button>
          </div>
        </div>
        <div class="flex min-h-0 flex-col">
          <div class="px-3 py-1 text-[11px] tracking-wide text-muted-foreground uppercase">Modifier</div>
          <div class="min-h-0 flex-1 overflow-y-auto" data-name="terminologyModifiers">
            <button v-if="modifiers.length" type="button" class="block w-full px-3 py-1 text-left text-[13px]"
              :class="modifier === '' ? 'bg-accent text-foreground' : 'hover:bg-accent/40'"
              @click="modifier = ''">(none)</button>
            <button v-for="m in modifiers" :key="m.codeValue" type="button"
              class="flex w-full items-center gap-2 px-3 py-1 text-left text-[13px]"
              :class="m.codeValue === modifier ? 'bg-accent text-foreground' : 'hover:bg-accent/40'"
              @click="modifier = m.codeValue">
              <span class="h-3 w-3 shrink-0 rounded-sm" :style="{ background: m.color }" />{{ m.name }}
            </button>
            <div v-if="!modifiers.length" class="px-3 py-1 text-[12px] text-muted-foreground">
              This type has none.
            </div>
          </div>
        </div>
      </div>

      <!-- The segment's name and colour: the terminology's, or one's own -->
      <div class="grid grid-cols-[auto_1fr_auto] items-center gap-x-2 gap-y-1 border-t border-input px-3 py-2 text-[13px]">
        <span class="text-muted-foreground">Name</span>
        <input :value="resultingName" data-name="terminologyName"
          class="h-7 min-w-0 rounded-md border border-input bg-background px-2 text-[13px] text-foreground outline-none focus:border-primary"
          :class="ownName !== null ? 'border-highlight/60' : ''"
          @change="setOwnName(($event.target as HTMLInputElement).value)" />
        <button type="button" class="rounded p-1 text-muted-foreground hover:text-highlight disabled:opacity-30" :disabled="ownName === null"
          title="Back to the name the terminology gives" data-name="terminologyNameReset" @click="ownName = null"><RotateCcw :size="14" /></button>
        <span class="text-muted-foreground">Color</span>
        <div class="flex items-center gap-2">
          <input type="color" :value="resultingColor" data-name="terminologyColor" class="h-6 w-8 cursor-pointer rounded border border-input bg-transparent p-0"
            @input="ownColor = ($event.target as HTMLInputElement).value" />
          <span class="text-[12px] text-muted-foreground">{{ ownColor !== null ? "your own" : "as the terminology recommends" }}</span>
        </div>
        <button type="button" class="rounded p-1 text-muted-foreground hover:text-highlight disabled:opacity-30" :disabled="ownColor === null"
          title="Back to the colour the terminology recommends" data-name="terminologyColorReset" @click="ownColor = null"><RotateCcw :size="14" /></button>
      </div>

      <div class="flex items-center gap-2 border-t border-input px-3 py-2">
        <span class="h-4 w-4 shrink-0 rounded-sm" :style="{ background: resultingColor }" />
        <span class="flex-1 truncate text-[13px] text-foreground">{{ resultingName }}</span>
        <span v-if="error" class="truncate text-[12px] text-red-400">{{ error }}</span>
        <button type="button" class="rounded-md px-3 py-1 text-[13px] text-foreground hover:bg-accent"
          @click="emit('close')">Cancel</button>
        <button type="button" data-name="terminologyApply" :disabled="!type"
          class="rounded-md bg-highlight px-3 py-1 text-[13px] text-background disabled:opacity-40"
          @click="apply">Select</button>
      </div>
    </div>
  </div>
</template>
