# Extensions built against the SlicerWeb build tree (Slicer_DIR=/build/slicer, see cmake/SlicerWebSDK.cmake).
# Which ones: the extension description files in $SW_EXTENSIONS_DIR (extensions/ of this repository
# unless build.ps1 is given another folder; see docs/extensions.md). Each is fetched at the revision
# its description names, built as Slicer's extension build builds it (superbuild included), and
# installed into $SW_INSTALL/ext/<Name> together with the Python packages it asks for; then all are
# packaged as wheels in $SW_DIST_ROOT/extensions.
# SW_EXTENSIONS limits what is built this time (e.g. SW_EXTENSIONS="SlicerHeart"); the others keep
# what an earlier build installed.
source /work/scripts/env.sh
source /work/scripts/fetch.sh
tool() { ls "$SW_INSTALL"/vtk-compiletools/bin/$1-* | head -1; }
SLICER_VERSION_DIR=$(basename "$(ls -d "$SW_INSTALL"/slicer/lib/Slicer-*)")   # Slicer-X.Y
EXT_BUILD=$SW_BUILD/ext
EXT_INSTALL=$SW_INSTALL/ext
# Everything a CMake project needs to be built for SlicerWeb - the Pyodide toolchain, the side-module
# flags, the stand-ins for OpenGL and zlib, the Python and VTK wrapping tools - is in a toolchain
# file, named in the environment (CMAKE_TOOLCHAIN_FILE) rather than on a command line. Every CMake
# configure reads it: the extension's, and those of the projects an extension's superbuild adds
# (VMTK, IGSIO), and of the projects those add in turn, none of which pass a command line on.
# Settings are defaults (_INIT flags, cache values), so a project that sets its own keeps them.
TOOLCHAIN=$SW_BUILD/slicerweb-toolchain.cmake
cmake_string() { printf '[==[%s]==]' "$*"; }
cat > "$TOOLCHAIN" <<EOF
# Generated by scripts/stages/80-extensions.sh: builds a CMake project for SlicerWeb (WebAssembly
# side modules loaded by Pyodide).
# Flags first, as cache values: CMake keeps a cache value rather than making one from its defaults
# (which would add -O3 to the release flags), and Pyodide's toolchain, included below, builds its
# CMAKE_<LANG>_FLAGS on the cache value it finds. The _INIT values are what a superbuild hands on to
# the projects it adds (ep_common_c_flags). Set, not appended: CMake reads a toolchain file more than
# once.
set(CMAKE_C_FLAGS_INIT $(cmake_string "$SW_ABI_CFLAGS"))
set(CMAKE_CXX_FLAGS_INIT $(cmake_string "$SW_ABI_CFLAGS"))
set(CMAKE_C_FLAGS $(cmake_string "$SW_ABI_CFLAGS") CACHE STRING "")
set(CMAKE_CXX_FLAGS $(cmake_string "$SW_ABI_CFLAGS") CACHE STRING "")
set(CMAKE_C_FLAGS_RELEASE $(cmake_string "$SW_OPT_CFLAGS") CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE $(cmake_string "$SW_OPT_CFLAGS") CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_INIT $(cmake_string "$SW_SIDE_LDFLAGS"))
set(CMAKE_MODULE_LINKER_FLAGS_INIT $(cmake_string "$SW_SIDE_LDFLAGS"))
set(CMAKE_SHARED_LINKER_FLAGS $(cmake_string "$SW_SIDE_LDFLAGS") CACHE STRING "")
set(CMAKE_MODULE_LINKER_FLAGS $(cmake_string "$SW_SIDE_LDFLAGS") CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE $(cmake_string "$SW_OPT_LDFLAGS") CACHE STRING "")
set(CMAKE_MODULE_LINKER_FLAGS_RELEASE $(cmake_string "$SW_OPT_LDFLAGS") CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS "-fwasm-exceptions -sSUPPORT_LONGJMP=wasm -sMAIN_MODULE=2" CACHE STRING "")
include($(cmake_string "$SW_TOOLCHAIN_FILE"))
set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "")
set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(CMAKE_CROSSCOMPILING_EMULATOR /work/scripts/emulator.sh CACHE FILEPATH "")
set(CMAKE_C_COMPILER_LAUNCHER ccache CACHE STRING "")
set(CMAKE_CXX_COMPILER_LAUNCHER ccache CACHE STRING "")
set(BUILD_TESTING OFF CACHE BOOL "")
# OpenGL (WebGL) comes from Pyodide's main module, zlib too: headers only, placeholder libraries
set(OPENGL_INCLUDE_DIR $SW_EMPTY/include CACHE PATH "")
set(OPENGL_GLES2_INCLUDE_DIR $SW_EMPTY/include CACHE PATH "")
set(OPENGL_GLES3_INCLUDE_DIR $SW_EMPTY/include CACHE PATH "")
set(OPENGL_EGL_INCLUDE_DIR $SW_EMPTY/include CACHE PATH "")
set(OPENGL_GLX_INCLUDE_DIR $SW_EMPTY/include CACHE PATH "")
foreach(_lib gl gles2 gles3 egl opengl glx)
  set(OPENGL_\${_lib}_LIBRARY $SW_EMPTY/lib/libsw_empty.a CACHE FILEPATH "")
endforeach()
set(ZLIB_ROOT $SW_ZLIB CACHE PATH "")
set(ZLIB_INCLUDE_DIR $SW_ZLIB/include CACHE PATH "")
set(ZLIB_LIBRARY $SW_ZLIB/lib/libz_from_main_module.a CACHE FILEPATH "")
# Python modules are side modules too: their symbols come from Pyodide's main module
set(Python3_INCLUDE_DIR $PYTHON_INCLUDE_DIR CACHE PATH "")
set(Python3_SOABI $SW_PY_SOABI CACHE STRING "")
set(Python3_EXECUTABLE /usr/local/bin/python3.14 CACHE FILEPATH "")
set(PYTHON_INCLUDE_DIR $PYTHON_INCLUDE_DIR CACHE PATH "")
set(PYTHON_LIBRARY "" CACHE FILEPATH "")
set(VTK_UNDEFINED_SYMBOLS_ALLOWED ON CACHE BOOL "")
set(VTK_WRAP_HIERARCHY_EXE $(tool vtkWrapHierarchy) CACHE FILEPATH "")
set(VTK_WRAP_PYTHON_EXE $(tool vtkWrapPython) CACHE FILEPATH "")
set(VTK_WRAP_PYTHON_INIT_EXE $(tool vtkWrapPythonInit) CACHE FILEPATH "")
# SlicerWeb's FindOpenGL (the WebGL targets VTK's config refers to), ahead of Emscripten's own,
# which the Emscripten toolchain puts first and which lacks the components VTK asks for
list(PREPEND CMAKE_MODULE_PATH /work/cmake)
EOF
export CMAKE_TOOLCHAIN_FILE=$TOOLCHAIN CMAKE_GENERATOR=Ninja
COMMON_ARGS=(-Wno-dev -DSlicer_DIR="$SW_BUILD/slicer")

# Install the components used in the browser: libraries, Python modules, resources - and "Runtime",
# which on the desktop holds the executables (CLI modules, tools) but here holds what modules put
# there beside them, such as Isodose's colour table: the SDK builds no executables at all. Not
# "Development" (headers, CMake files).
install_components() { # build-dir prefix
  local comps c
  comps=$(grep -rhoP 'CMAKE_INSTALL_COMPONENT STREQUAL "\K[^"]+' "$1" --include=cmake_install.cmake | sort -u \
    | grep -vxE 'Development')
  for c in $comps; do
    cmake --install "$1" --component "$c" --prefix "$2"
  done
}

want() { [ -z "${SW_EXTENSIONS:-}" ] || [[ " $SW_EXTENSIONS " == *" $1 "* ]]; }
in_catalog() { [[ " ${CATALOG[*]} " == *" $1 "* ]]; }

# An extension is built as Slicer's extension build builds it: configured and built from its source,
# superbuild and all - an extension that needs a library (SlicerVMTK VMTK, SlicerIGSIO IGSIO) builds
# it itself, which is what the toolchain file above is for. Then what it installs is installed: its
# own build (in <build subdirectory>, "inner-build" for one with a superbuild), and what it lists in
# <Name>_CPACK_INSTALL_CMAKE_PROJECTS - the libraries its superbuild built, which Slicer's extension
# packaging takes from the same list.
build_extension() { # name build-subdirectory [cmake args...]
  local name=$1 sub=$2; shift 2
  log "extension $name"
  cmake -S "$SW_SRC/$name" -B "$EXT_BUILD/$name" "${COMMON_ARGS[@]}" "$@"
  cmake --build "$EXT_BUILD/$name" -j "$SW_JOBS"
  local inner=$EXT_BUILD/$name/$sub projects i
  [ -f "$inner/CMakeCache.txt" ] || { echo "$name was not built in $inner (build_subdirectory)"; exit 1; }
  install_components "$inner" "$EXT_INSTALL/$name"
  IFS=';' read -ra projects <<<"$(sed -n "s/^${name}_CPACK_INSTALL_CMAKE_PROJECTS:[A-Z]*=//p" "$inner/CMakeCache.txt")"
  for ((i = 0; i + 3 < ${#projects[@]}; i += 4)); do  # build-dir;project;component;/
    log "$name: ${projects[i+1]} (${projects[i+2]})"
    cmake --install "${projects[i]}" --component "${projects[i+2]}" --prefix "$EXT_INSTALL/$name"
  done
}

# One extension of the catalog (the plan below calls this, dependencies first). The extensions it
# depends on are handed to it as the Slicer extension build hands them: <Name>_DIR, the build tree
# of each, where its <Name>Config.cmake is.
declare -A SUBDIRECTORY
extension() { # name url revision description build-subdirectory "dependencies" [cmake options...]
  local name=$1 url=$2 rev=$3 description=$4 sub=$5 deps=$6 dep; shift 6
  SUBDIRECTORY[$name]=$sub
  want "$name" || return 0
  fetch "$name" "$url" "$rev"
  rm -rf "$EXT_INSTALL/$name"
  local dep_args=()
  for dep in $deps; do
    in_catalog "$dep" && dep_args+=(-D"${dep}_DIR=$EXT_BUILD/$dep/${SUBDIRECTORY[$dep]}")
  done
  build_extension "$name" "$sub" "${dep_args[@]}" "$@"
  python3.14 /work/scripts/extension_catalog.py python-packages "$description" "$EXT_INSTALL/$name"
}

log "extensions of $SW_EXTENSIONS_DIR"
plan=$(python3.14 /work/scripts/extension_catalog.py plan "$SW_EXTENSIONS_DIR")
echo "$plan"
eval "$(grep '^CATALOG=' <<<"$plan")"
for name in ${SW_EXTENSIONS:-}; do
  in_catalog "$name" || { echo "SW_EXTENSIONS names $name, which is not in $SW_EXTENSIONS_DIR"; exit 1; }
done
# What an earlier build installed of extensions that are no longer in the catalog is not packaged.
mkdir -p "$EXT_INSTALL"
for dir in "$EXT_INSTALL"/*/; do
  [ -d "$dir" ] || continue
  in_catalog "$(basename "$dir")" || { log "removing $(basename "$dir") (not in the catalog)"; rm -rf "$dir"; }
done
eval "$plan"

log "extension wheels"
python3.14 /work/scripts/make_wheels.py --extensions-only --install "$SW_INSTALL" --src "$SW_SRC" \
  --build "$SW_BUILD" --extensions-out "$SW_DIST_ROOT/extensions"
