import { chromium } from "playwright-core";
const browser = await chromium.launch({ channel: "chrome", headless: true, args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const page = await (await browser.newContext({ viewport: { width: 1400, height: 900 } })).newPage();
page.on("pageerror", (e) => console.log("[pageerror] " + String(e).slice(0, 200)));
await page.goto("http://localhost:5173/?sample=MRHead");
await page.waitForFunction(() => window.slicerWeb?.bridge && document.querySelector("canvas"), null, { timeout: 300000 });
await page.waitForTimeout(5000);
const text = async (e) => String(await page.evaluate((c) => window.slicerWeb.bridge.evalPython(c, "eval"), e)).replace(/^['"]|['"]$/g, "");
const call = (m, a) => page.evaluate(([x, y]) => window.slicerWeb.bridge.call(x, y), [m, a]).catch((e) => ({ error: String(e.message).slice(0, 200) }));
const id = await text(`slicer.util.getNodesByClass("vtkMRMLScalarVolumeNode")[0].GetID()`);
console.log("info before:", JSON.stringify(await call("volumeRenderingInfo", [id])).slice(0, 160));
console.log("enable     :", JSON.stringify(await call("setVolumeRendering", [id, { visible: true }])).slice(0, 160));
await page.waitForTimeout(2500);
console.log("info after :", JSON.stringify(await call("volumeRenderingInfo", [id])).slice(0, 300));
console.log("preset     :", JSON.stringify(await call("setVolumeRendering", [id, { preset: "MR-Default", visible: true }])).slice(0, 160));
await page.waitForTimeout(1500);
console.log("info again :", JSON.stringify(await call("volumeRenderingInfo", [id])).slice(0, 300));
await browser.close();
