# SlicerWeb CMake helpers (also installed in the SlicerWeb SDK for extensions).

include(CMakeParseArguments)

#-----------------------------------------------------------------------------
# slicerweb_add_module_initializer(
#   NAME <Name>
#   [DISPLAYABLE_MANAGER_LIBRARIES <lib>...]   # libraries whose object factories must be registered
#   [SLICE_DISPLAYABLE_MANAGERS <class>...]     # registered in the slice view factory
#   [THREED_DISPLAYABLE_MANAGERS <class>...]    # registered in the 3D view factory
#   [INSTALL_LIB_DIR <dir>]
#   )
#
# In desktop Slicer, the Qt module class (qSlicer<Module>Module::setup()) initializes the object
# factory of the module's displayable manager library (VTK_MODULE_INIT) and registers the displayable
# managers by class name. This function generates the Qt-free equivalent: a Python-wrapped class
#   vtkSlicerWeb<Name>Initializer
# with a static Initialize() method, called by the SlicerWeb module manager when the module package
# is loaded.
#-----------------------------------------------------------------------------
function(slicerweb_add_module_initializer)
  cmake_parse_arguments(MY "" "NAME;INSTALL_LIB_DIR"
    "DISPLAYABLE_MANAGER_LIBRARIES;SLICE_DISPLAYABLE_MANAGERS;THREED_DISPLAYABLE_MANAGERS" ${ARGN})
  if(NOT MY_NAME)
    message(FATAL_ERROR "slicerweb_add_module_initializer: NAME is required")
  endif()
  if(NOT MY_INSTALL_LIB_DIR)
    set(MY_INSTALL_LIB_DIR ${Slicer_INSTALL_QTLOADABLEMODULES_LIB_DIR})
  endif()

  set(lib_name vtkSlicerWeb${MY_NAME}Initializer)
  string(TOUPPER ${lib_name} LIB_NAME_UPPER)
  set(_dir ${CMAKE_CURRENT_BINARY_DIR}/${lib_name})
  file(MAKE_DIRECTORY ${_dir})

  set(_module_inits "")
  foreach(_lib IN LISTS MY_DISPLAYABLE_MANAGER_LIBRARIES)
    string(APPEND _module_inits "VTK_MODULE_INIT(${_lib});\n")
  endforeach()
  set(_registrations "")
  foreach(_dm IN LISTS MY_SLICE_DISPLAYABLE_MANAGERS)
    string(APPEND _registrations "  vtkSlicerWebRegister(vtkMRMLSliceViewDisplayableManagerFactory::GetInstance(), \"${_dm}\");\n")
  endforeach()
  foreach(_dm IN LISTS MY_THREED_DISPLAYABLE_MANAGERS)
    string(APPEND _registrations "  vtkSlicerWebRegister(vtkMRMLThreeDViewDisplayableManagerFactory::GetInstance(), \"${_dm}\");\n")
  endforeach()

  file(WRITE ${_dir}/${lib_name}.h.in [=[
// Generated by slicerweb_add_module_initializer(). Do not edit.
#ifndef @lib_name@_h
#define @lib_name@_h

#include "@lib_name@Export.h"
#include <vtkObject.h>

/// Registers object factories and displayable managers of the @MY_NAME@ modules
/// (Qt-free equivalent of the setup() method of their Qt module classes).
class @LIB_NAME_UPPER@_EXPORT @lib_name@ : public vtkObject
{
public:
  static @lib_name@* New();
  vtkTypeMacro(@lib_name@, vtkObject);

  /// Register displayable managers. Safe to call multiple times.
  static void Initialize();

protected:
  @lib_name@() = default;
  ~@lib_name@() override = default;

private:
  @lib_name@(const @lib_name@&) = delete;
  void operator=(const @lib_name@&) = delete;
};

#endif
]=])
  file(WRITE ${_dir}/${lib_name}.cxx.in [=[
// Generated by slicerweb_add_module_initializer(). Do not edit.
#include "@lib_name@.h"

#include <vtkMRMLSliceViewDisplayableManagerFactory.h>
#include <vtkMRMLThreeDViewDisplayableManagerFactory.h>
#include <vtkObjectFactory.h>

// Register the object factories of the displayable manager libraries when this library is loaded.
#include <vtkAutoInit.h>
@_module_inits@
vtkStandardNewMacro(@lib_name@);

namespace
{
void vtkSlicerWebRegister(vtkMRMLDisplayableManagerFactory* factory, const char* name)
{
  if (!factory->IsDisplayableManagerRegistered(name))
  {
    factory->RegisterDisplayableManager(name);
  }
}
}

void @lib_name@::Initialize()
{
@_registrations@}
]=])
  configure_file(${_dir}/${lib_name}.h.in ${_dir}/${lib_name}.h @ONLY)
  configure_file(${_dir}/${lib_name}.cxx.in ${_dir}/${lib_name}.cxx @ONLY)

  set(_srcs ${_dir}/${lib_name}.cxx)
  add_library(${lib_name} ${_srcs})
  target_include_directories(${lib_name} PUBLIC ${_dir} ${Slicer_Libs_INCLUDE_DIRS} ${MRMLDisplayableManager_INCLUDE_DIRS})
  target_link_libraries(${lib_name} PUBLIC MRMLDisplayableManager ${MY_DISPLAYABLE_MANAGER_LIBRARIES})
  include(GenerateExportHeader)
  generate_export_header(${lib_name} EXPORT_FILE_NAME ${_dir}/${lib_name}Export.h)
  set_target_properties(${lib_name} PROPERTIES
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/${Slicer_QTLOADABLEMODULES_LIB_DIR}")
  install(TARGETS ${lib_name}
    LIBRARY DESTINATION ${MY_INSTALL_LIB_DIR} COMPONENT RuntimeLibraries
    ARCHIVE DESTINATION ${MY_INSTALL_LIB_DIR} COMPONENT Development)

  set(${lib_name}_INCLUDE_DIRS ${_dir} CACHE INTERNAL "" FORCE)
  include(vtkMacroKitPythonWrap)
  vtkMacroKitPythonWrap(
    KIT_NAME ${lib_name}
    KIT_SRCS ${_srcs}
    KIT_INSTALL_BIN_DIR ${MY_INSTALL_LIB_DIR}
    KIT_INSTALL_LIB_DIR ${MY_INSTALL_LIB_DIR}
    )
endfunction()
