# Build-tree SDK for SlicerWeb extensions.
#
# Desktop Slicer extensions are configured against a Slicer build tree (Slicer_DIR), whose
# SlicerConfig.cmake provides the Slicer libraries (exported targets), include directories, install
# layout and the CMake macros (Slicer_USE_FILE). This file generates the same for the SlicerWeb
# (WebAssembly, Qt-free) build tree:
#
#   <build>/SlicerWebTargets.cmake  all Slicer library targets built by this project
#   <build>/SlicerConfig.cmake      variables captured from this configuration, then the targets
#
# Extensions are then configured with -DSlicer_DIR=<build>; UseSlicerWeb.cmake (Slicer_USE_FILE)
# provides the module macros, building the Qt-free parts of loadable modules (MRML, Logic,
# VTKWidgets, MRMLDM) and Python scripted modules.

# ---------------------------------------------------------------------------- targets
function(_slicerweb_collect_targets dir out_var)
  get_property(_targets DIRECTORY "${dir}" PROPERTY BUILDSYSTEM_TARGETS)
  get_property(_subdirs DIRECTORY "${dir}" PROPERTY SUBDIRECTORIES)
  foreach(_sub IN LISTS _subdirs)
    _slicerweb_collect_targets("${_sub}" _sub_targets)
    list(APPEND _targets ${_sub_targets})
  endforeach()
  set(${out_var} ${_targets} PARENT_SCOPE)
endfunction()

_slicerweb_collect_targets("${CMAKE_SOURCE_DIR}" _all_targets)
set(_sdk_targets)
foreach(_t IN LISTS _all_targets)
  get_target_property(_type ${_t} TYPE)
  if(_type MATCHES "^(SHARED_LIBRARY|MODULE_LIBRARY|STATIC_LIBRARY|INTERFACE_LIBRARY)$"
      AND NOT _t MATCHES "^(VTKCompileTools|SlicerWeb)")
    list(APPEND _sdk_targets ${_t})
  endif()
endforeach()
export(TARGETS ${_sdk_targets} FILE "${CMAKE_BINARY_DIR}/SlicerWebTargets.cmake")
# vtkAddon's own config in this build tree includes a targets file that nothing exports; the
# vtkAddon target is among the targets exported above, so an empty one satisfies the include.
# (An extension built with Slicer_EXTENSION_SOURCE_DIRS set - SlicerIGT - finds vtkAddon itself.)
file(WRITE "${CMAKE_BINARY_DIR}/Libs/vtkAddon/vtkAddonTargets.cmake" "# vtkAddon is exported with the Slicer targets (SlicerWebTargets.cmake)\n")

# ---------------------------------------------------------------------------- variables
# Captured with bracket arguments, so values need no escaping.
set(_sdk_var_regex
  "^(Slicer_|MRML_|VTK_WRAP_|VTK_DIR$|ITK_DIR$|Teem_DIR$|SlicerExecutionModel_DIR$|vtkAddon_|Python3_|PYTHON_|RapidJSON_|JsonCpp_|LibArchive_|GENERATECLP_|ModuleDescriptionParser_)|_INCLUDE_DIRS$|_WRAP_HIERARCHY_FILE$")
set(_sdk_var_exclude_regex "^(Slicer_TARGETS|Slicer_USE_FILE|Slicer_DIR)$|^_")
get_cmake_property(_vars VARIABLES)
set(_config "# Generated by SlicerWeb (cmake/SlicerWebSDK.cmake). Do not edit.\n")
string(APPEND _config "# SlicerWeb build tree configuration for extensions (Qt-free Slicer for WebAssembly).\n\n")
# An extension may ask for the prerequisites before its project() - find_package(Slicer COMPONENTS
# ConfigurePrerequisites), then project(), then find_package(Slicer) - as Slicer's own config
# allows. Before project() no language is enabled, and finding VTK then fails on Threads; so that
# first call sets what a project() needs and returns, as Slicer's config does.
string(APPEND _config "if(\"ConfigurePrerequisites\" IN_LIST Slicer_FIND_COMPONENTS)\n")
string(APPEND _config "  set(Slicer_USE_CONFIGUREPREREQUISITES TRUE)\n")
string(APPEND _config "  set(Slicer_FOUND TRUE)\n")
string(APPEND _config "  return()\n")
string(APPEND _config "endif()\n\n")
string(APPEND _config "set(Slicer_DIR [==[${CMAKE_BINARY_DIR}]==])\n")
string(APPEND _config "set(SlicerWeb TRUE)\n")
string(APPEND _config "set(SlicerWeb_SOURCE_DIR [==[${CMAKE_SOURCE_DIR}]==])\n")
string(APPEND _config "set(SlicerWeb_CMAKE_DIR [==[${CMAKE_SOURCE_DIR}/cmake]==])\n")
string(APPEND _config "set(Slicer_USE_FILE [==[${CMAKE_SOURCE_DIR}/cmake/UseSlicerWeb.cmake]==])\n")
string(APPEND _config "set(Slicer_EXTENSION_GENERATE_CONFIG [==[${CMAKE_SOURCE_DIR}/cmake/SlicerWebEmpty.cmake]==])\n")
string(APPEND _config "set(Slicer_EXTENSION_CPACK [==[${CMAKE_SOURCE_DIR}/cmake/SlicerWebEmpty.cmake]==])\n")
string(APPEND _config "set(Slicer_CMAKE_DIR [==[${Slicer_SOURCE_DIR}/CMake]==])\n")
string(APPEND _config "set(Slicer_EXTENSIONS_CMAKE_DIR [==[${Slicer_SOURCE_DIR}/Extensions/CMake]==])\n")
string(APPEND _config "set(vtkAddon_CMAKE_DIR [==[${vtkAddon_SOURCE_DIR}/CMake]==])\n")
string(APPEND _config "set(Slicer_EXPORT_HEADER_TEMPLATE [==[${Slicer_EXPORT_HEADER_TEMPLATE}]==])\n")
string(APPEND _config "set(Slicer_LOGOS_RESOURCE [==[]==])\n")
string(APPEND _config "set(Slicer_VTK_WRAP_HIERARCHY_DIR [==[${CMAKE_BINARY_DIR}]==])\n\n")
foreach(_v IN LISTS _vars)
  if(_v MATCHES "${_sdk_var_regex}" AND NOT _v MATCHES "${_sdk_var_exclude_regex}")
    # Include directory lists are accumulated by Slicer macros in the cache (CACHE INTERNAL): a
    # normal variable would hide what the extension appends.
    get_property(_cache_type CACHE "${_v}" PROPERTY TYPE)
    if(_cache_type STREQUAL "INTERNAL")
      string(APPEND _config "set(${_v} [==[${${_v}}]==] CACHE INTERNAL \"\" FORCE)\n")
    else()
      string(APPEND _config "set(${_v} [==[${${_v}}]==])\n")
    endif()
  endif()
endforeach()
string(APPEND _config [==[

# Dependencies referenced by the exported targets
if(NOT DEFINED SlicerWeb_SDK_TARGETS_INCLUDED)
  set(SlicerWeb_SDK_TARGETS_INCLUDED TRUE)
  # FindOpenGL.cmake of SlicerWeb (WebGL targets referenced by VTK)
  list(PREPEND CMAKE_MODULE_PATH "${SlicerWeb_CMAKE_DIR}")
  find_package(VTK REQUIRED)
  find_package(ITK REQUIRED)
  find_package(Teem REQUIRED NO_MODULE)
  find_package(SlicerExecutionModel REQUIRED)
  find_package(RapidJSON REQUIRED)  # header-only; linked by the Markups MRML library
  include("${Slicer_DIR}/SlicerWebTargets.cmake")
endif()
set(Slicer_FOUND TRUE)
]==])
file(WRITE "${CMAKE_BINARY_DIR}/SlicerConfig.cmake" "${_config}")
message(STATUS "SlicerWeb extension SDK: ${CMAKE_BINARY_DIR}/SlicerConfig.cmake (${CMAKE_BINARY_DIR}/SlicerWebTargets.cmake)")
